name: Async Checks API

on:
  workflow_dispatch:
    inputs:
      checksObject:
        description: ''
        required: false
        default: ''

permissions:
  checks: write

env:
  GKE_ZONE: 'us-central1'
  GKE_REGION: 'us-central1'
  GKE_PROJECT: 'unitykubernetesbuilder'
  GKE_CLUSTER: 'game-ci-github-pipelines'
  GCP_LOGGING: true
  GCP_PROJECT: unitykubernetesbuilder
  GCP_LOG_FILE: ${{ github.workspace }}/cloud-runner-logs.txt
  AWS_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2
  AWS_STACK_NAME: game-ci-github-pipelines
  CLOUD_RUNNER_BRANCH: ${{ github.ref }}
  CLOUD_RUNNER_DEBUG: true
  CLOUD_RUNNER_DEBUG_TREE: true
  DEBUG: true
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PROJECT_PATH: test-project
  UNITY_VERSION: 2019.3.15f1
  USE_IL2CPP: false

jobs:
  asyncChecks:
    name: Async Checks
    if: github.event.event_type != 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - timeout-minutes: 180
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          PROJECT_PATH: test-project
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PRIVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PLATFORM: StandaloneWindows64
          cloudRunnerTests: true
          versioning: None
          CLOUD_RUNNER_CLUSTER: local-docker
          AWS_STACK_NAME: game-ci-github-pipelines
          CHECKS_UPDATE: ${{ github.event.inputs.checksObject }}
        run: |
          git clone -b cloud-runner-develop https://github.com/game-ci/unity-builder
          cd unity-builder
          yarn
          ls
          yarn run cli -m checks-update
